rm -rf output
./build/raytracer scenes/scene01.xml
./build/raytracer scenes/scene02.xml
./build/raytracer scenes/scene03.xml
./build/raytracer scenes/scene04.xml
./build/raytracer scenes/scene05.xml
./build/raytracer scenes/scene06.xml
./build/raytracer scenes/scene07.xml
./build/raytracer scenes/scene08.xml
./build/raytracer scenes/scene09.xml
./build/raytracer scenes/scene10.xml
./build/raytracer scenes/scene11.xml
./build/raytracer scenes/scene12.xml
./build/raytracer scenes/scene13.xml
./build/raytracer scenes/scene14.xml
./build/raytracer scenes/scene15.xml
./build/raytracer scenes/scene16.xml
./build/raytracer scenes/scene17.xml
./build/raytracer scenes/scene18.xml
./build/raytracer scenes/scene19.xml
./build/raytracer scenes/scene20.xml
./build/raytracer scenes/scene21.xml
./build/raytracer scenes/scene22.xml
./build/raytracer scenes/scene23.xml
./build/raytracer scenes/scene24.xml
./build/raytracer scenes/scene25.xml
./build/raytracer scenes/scene26.xml
./build/raytracer scenes/scene27.xml
./build/raytracer scenes/scene27.1.xml
./build/raytracer scenes/scene28.xml
./build/raytracer scenes/scene28.1.xml
./build/raytracer scenes/scene29.xml
./build/raytracer scenes/scene30.xml
./build/raytracer scenes/scene31.xml
./build/raytracer scenes/scene32.xml
./build/raytracer scenes/scene33.xml
./build/raytracer scenes/scene34.xml
./build/raytracer scenes/scene35.xml
./build/raytracer scenes/scene36.xml
./build/raytracer scenes/scene37.xml
./build/raytracer scenes/scene38.xml
./build/raytracer scenes/scene39.xml
./build/raytracer scenes/scene40.xml
./build/raytracer scenes/scene41.xml
./build/raytracer scenes/scene42.xml
./build/raytracer scenes/scene43.xml
./build/raytracer scenes/scene44.xml
./build/raytracer scenes/scene45.xml
./build/raytracer scenes/scene46.xml
./build/raytracer scenes/scene47.xml
./build/raytracer scenes/scene48.xml
./build/raytracer scenes/scene49.xml
./build/raytracer scenes/scene50.xml
./build/raytracer scenes/scene51.xml
